### ISSUE TITLE
Eval Security

### ISSUE THREAD

**Issue by imdaveead** [Yamboy1/discord-donuts#1]
On [eval.cmd.js](https://github.com/Yamboy1/discord-donuts/blob/yams-rewrite/commands/private/eval.cmd.js), you could easily evaluate the bot's token. This is slightly prevented with
```js
if (toEval.includes("token")) return ...
```
but this is not enough as you can do
```
d!eval bot["to" + "ken"]
> Censored
```
Ok, so we got past block 1, but theres another line that removes the token from the content
```js
const array = [
    escapeRegex(token),
];
let regex = new RegExp(array.join("|"), "g");
com = com.replace(regex, "Censored");
```
And we can super easily bypass that by making some manipulation to the string
```
d!eval bot["to" + "ken"].split("").join(" ")
> The token, seperated by spaces
```
Hunter pointed out you can also use a `message.channel.send` as well.
```
d!eval message.channel.send(bot["to" + "ken"]);
> The token
> Eval Complete
```

**Comment by imdaveead** [comment]
I should also point out that a while true loop `while (true) { /* Do nothing */ }` will freeze the bot

**Comment by hparcells** [comment]
You can also do `d!eval let bot2 = bot; msg.channel.send(bot2.token)` for a better formatted token.

**Comment by Yamboy1** [comment]
Thanks for this @imdaveead, I will look into this, however, as we already habe restrictions on who can use the command, it will not be of the highest priority

**Comment by Filip9696** [comment]
Yes you have restrictions on who can issue the command, however these people are humans selected by other humans, and humans are dumb and unpredictable. Security issues are not solved by restricting others, you're best bet would be removing the eval command completely or restricting it to yourself.
