### ISSUE TITLE
Set the presence of the bot

### ISSUE THREAD

**Issue by Yamboy1** [Yamboy1/discord-donuts#23]
currently the bot has no presence, we should add that. Heres the list that the current bot uses:
```js
["Cooking Donuts...", "Donuts!", "Cookin' Donuts", "d!order Donuts", "<3 Donuts", "with Donuts"];
```
and it currently runs every 300 seconds

**Comment by hparcells** [comment]
Sure

**Comment by hparcells** [comment]
Done. Waiting for push permission.

**Comment by hparcells** [comment]
Never mind. I'll make a pull request.
