### ISSUE TITLE
Commands to add

### ISSUE THREAD

**Issue by Yamboy1** [Yamboy1/discord-donuts#3]
There are a few commands that still need to be implmented from the old bot:

- [x] ~~permissions.cmd.js~~ Not required
- [x] help.cmd.js
- [x] prefix.cmd.js
- [x] uptime.cmd.js
- [x] feedback.cmd.js
- [x] tip.cmd.js 
- [x] donate.cmd.js
- [x] upvote.cmd.js

**Comment by hparcells** [comment]
Don’t we need feedback and tip too?

**Comment by Yamboy1** [comment]
Yes we do indeed

**Comment by Yamboy1** [comment]
In the case of the donate command, heres the patreon: https://patreon.com/discorddonuts

**Comment by Yamboy1** [comment]
also, the upvote command is basically a link to https://www.its-mustard.me/upvote, but with a bit of explanation

**Comment by Yamboy1** [comment]
a new table is probably required for the prefix command. if so, the id column should be `CHAR(18)`, any variable length strings should be `TEXT`, and numbers as `INTEGER`

**Comment by hparcells** [comment]
donate.cmd.js and upvote.cmd.js done in next pull request.
