### ISSUE TITLE
A duplicate id could be created

### ISSUE THREAD

**Issue by Yamboy1** [Yamboy1/discord-donuts#30]
As sql uses unique id's, we should always check when generating an ID, that the ID is unique, because we'll get some weird shit happening if we don't check this

**Comment by hparcells** [comment]
But th isn’t this like super rare and generating two identical IDs the way we are doing super rare?

**Comment by Yamboy1** [comment]
As more and more orders are added to the table, and remember, these are being kept afaik, the chance increases

On Oct 27, 2018 11:47 PM, Hunter Parcells <notifications@github.com> wrote:

But th isn’t this like super rare and generating two identical IDs the way we are doing super rare?

**Comment by hparcells** [comment]
done in pull request.
